//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_WebAPI_AngularJs_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Phone_Calls = new HashSet<Phone_Calls>();
        }
    
        public int Customer_ID { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Address { get; set; }
        public string Mobile { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Whatsapp { get; set; }
        public string Email { get; set; }
        public string Customer_Code { get; set; }
        public string Nationality { get; set; }
        public string Resolved_Residence { get; set; }
        public string Details { get; set; }
        public string Occupation { get; set; }
        public string Introduced_By { get; set; }
        public Nullable<System.DateTime> Entry_Date { get; set; }
        public string Last_Update { get; set; }
        public Nullable<System.DateTime> Last_Modified_In { get; set; }
        public string Salesman { get; set; }
        public string Client_Source { get; set; }
        public string Customer_Rating { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phone_Calls> Phone_Calls { get; set; }
    }
}
